name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install kamal
        run: gem install kamal

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Create Kamal secrets directory
        run: |
          mkdir -p .kamal/secrets
          echo "${{ secrets.RAILS_MASTER_KEY }}" > .kamal/secrets/RAILS_MASTER_KEY
          echo "${{ secrets.KAMAL_REGISTRY_PASSWORD }}" > .kamal/secrets/KAMAL_REGISTRY_PASSWORD

      - name: Deploy to production
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
        run: |
          kamal deploy
